version: '3.8'

networks:
  rmoff_kafka:
    name: rmoff_kafka

services:

  zookeeper:
    image: .../confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    networks:
      - rmoff_kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181" # Expose the zookeeper client port to allow host clients to connect

  kafka1:
    image: .../confluentinc/cp-kafka:latest
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092" # Expose the kafka port to allow host clients to connect
    networks:
      - rmoff_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092 # try change this to localhost:9092 and bootstrap servers in conf files also
      KAFKA_ADVERTISED_HOST_NAME: kafka1

  kafka2:
    image: .../confluentinc/cp-kafka:latest
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9091:9091" # Expose the kafka port to allow host clients to connect
    networks:
      - rmoff_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9091
      KAFKA_ADVERTISED_HOST_NAME: kafka2

  kafka3:
    image: .../confluentinc/cp-kafka:latest
    container_name: kafka3
    hostname: kafka3
    ports:
      - "9093:9093" # Expose the kafka port to allow host clients to connect
    networks:
      - rmoff_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9093
      KAFKA_ADVERTISED_HOST_NAME: kafka3

  kafka-rest:
    image: .../confluentinc/cp-kafka-rest:latest
    hostname: kafka-rest
    ports:
      - "8083:8082" # Mapped 1 port higher to avoid conflict with McAfee
    networks:
      - rmoff_kafka
    depends_on:
      - zookeeper
      - schema-registry
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://kafka-rest:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka1:8082,kafka2:8083

  schema-registry:
    image: .../confluentinc/cp-schema-registry:latest
    networks:
      - rmoff_kafka
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_DEBUG: "true"
    ports:
      - "8082:8081" # Expose schema registry to host clients. Mapped 1 port higher to avoid conflict with McAfee ?
